#include "elog.hpp"

#include <catch2/catch_test_macros.hpp>

#include <string>
#include <vector>

namespace {

// As portage's mod_save_summary writes two entries.
constexpr std::string_view summary =
    ">>> Messages generated by process 12 on 2026-09-30 11:41:39 PDT for package a/b-1:\n"
    "\n"
    "LOG: postinst\n"
    "Build the store once:\n"
    "\n"
    "  egraph rebuild\n"
    "WARN: postinst\n"
    "Careful.\n"
    "\n"
    ">>> Messages generated by process 13 on 2026-09-30 11:42:00 PDT for package c/d-2:\n"
    "\n"
    "QA: other\n"
    "QA Notice: LOG: postinst is a message here\n"
    "\n";

} // namespace

TEST_CASE("the summary log's entries are read by package, class and phase") {
    const auto entries = egraph::parse_elog_summary(summary);
    REQUIRE(entries.size() == 2);
    CHECK(entries.at(0).package == "a/b-1");
    REQUIRE(entries.at(0).messages.size() == 2);
    CHECK(entries.at(0).messages.at(0).type == "LOG");
    CHECK(entries.at(0).messages.at(0).phase == "postinst");
    // A blank line inside a message stays.
    CHECK(entries.at(0).messages.at(0).lines ==
          std::vector<std::string>{"Build the store once:", "", "  egraph rebuild"});
    CHECK(entries.at(0).messages.at(1).type == "WARN");
    CHECK(entries.at(0).messages.at(1).lines == std::vector<std::string>{"Careful."});
    CHECK(entries.at(1).package == "c/d-2");
    REQUIRE(entries.at(1).messages.size() == 1);
    CHECK(entries.at(1).messages.at(0).type == "QA");
    CHECK(entries.at(1).messages.at(0).phase == "other");
    CHECK(entries.at(1).messages.at(0).lines ==
          std::vector<std::string>{"QA Notice: LOG: postinst is a message here"});
}

TEST_CASE("text before the first entry, and nothing at all, are no entries") {
    CHECK(egraph::parse_elog_summary("").empty());
    CHECK(egraph::parse_elog_summary("the tail of an earlier entry\n").empty());
    const auto entries = egraph::parse_elog_summary(
        std::string{"rest of an entry\n\n"}.append(summary.substr(summary.find(">>> M", 1))));
    REQUIRE(entries.size() == 1);
    CHECK(entries.front().package == "c/d-2");
}

TEST_CASE("a header line only counts with a class and phase portage writes") {
    const auto entries = egraph::parse_elog_summary(
        ">>> Messages generated by process 1 on now for package a/b-1:\n\nLOG: postinst\n"
        "NOTE: postinst\nLOG: somewhere\n\n");
    REQUIRE(entries.size() == 1);
    REQUIRE(entries.front().messages.size() == 1);
    CHECK(entries.front().messages.front().lines ==
          std::vector<std::string>{"NOTE: postinst", "LOG: somewhere"});
}

TEST_CASE("elog lines give each message line with its package, class and phase") {
    CHECK(egraph::elog_lines(egraph::parse_elog_summary(summary)) ==
          std::vector<std::string>{
              "a/b-1\telog\tLOG\tpostinst\tBuild the store once:", "a/b-1\telog\tLOG\tpostinst\t",
              "a/b-1\telog\tLOG\tpostinst\t  egraph rebuild",
              "a/b-1\telog\tWARN\tpostinst\tCareful.",
              "c/d-2\telog\tQA\tother\tQA Notice: LOG: postinst is a message here"});
}
