#include "elog.hpp"

#include <algorithm>
#include <array>
#include <format>
#include <optional>
#include <utility>

namespace egraph {

namespace {

constexpr std::string_view header_lead = ">>> Messages generated by process ";
constexpr std::string_view header_package = " for package ";

// As portage's EBUILD_PHASES and the message classes elog knows.
constexpr std::array<std::string_view, 18> phases{
    "pretend", "setup",   "unpack",  "prepare",  "configure", "compile",
    "test",    "install", "package", "instprep", "preinst",   "postinst",
    "prerm",   "postrm",  "nofetch", "config",   "info",      "other"};
constexpr std::array<std::string_view, 5> types{"INFO", "LOG", "WARN", "ERROR", "QA"};

// The package an entry's header names, if line is one.
std::optional<std::string_view> header(std::string_view line) {
    if (!line.starts_with(header_lead) || !line.ends_with(':')) {
        return std::nullopt;
    }
    const auto at = line.rfind(header_package);
    if (at == std::string_view::npos) {
        return std::nullopt;
    }
    const auto start = at + header_package.size();
    return line.substr(start, line.size() - 1 - start);
}

// The class and phase of a message's first line, if line is one.
std::optional<std::pair<std::string_view, std::string_view>> message_start(std::string_view line) {
    const auto colon = line.find(": ");
    if (colon == std::string_view::npos) {
        return std::nullopt;
    }
    const auto type = line.substr(0, colon);
    const auto phase = line.substr(colon + 2);
    if (!std::ranges::contains(types, type) || !std::ranges::contains(phases, phase)) {
        return std::nullopt;
    }
    return std::pair{type, phase};
}

// Drops the blank lines that end an entry.
void trim(ElogEntry& entry) {
    if (entry.messages.empty()) {
        return;
    }
    auto& lines = entry.messages.back().lines;
    while (!lines.empty() && lines.back().empty()) {
        lines.pop_back();
    }
}

} // namespace

std::vector<ElogEntry> parse_elog_summary(std::string_view text) {
    std::vector<ElogEntry> entries;
    bool opened = false;
    while (!text.empty()) {
        const auto end = text.find('\n');
        const auto line = text.substr(0, end);
        text.remove_prefix(end == std::string_view::npos ? text.size() : end + 1);
        if (const auto package = header(line)) {
            if (!entries.empty()) {
                trim(entries.back());
            }
            entries.push_back({.package = std::string(*package), .messages = {}});
            // The blank line after a header is the log's own.
            opened = true;
            continue;
        }
        if (entries.empty()) {
            continue;
        }
        if (std::exchange(opened, false) && line.empty()) {
            continue;
        }
        auto& messages = entries.back().messages;
        if (const auto start = message_start(line)) {
            messages.push_back({.type = std::string(start->first),
                                .phase = std::string(start->second),
                                .lines = {}});
        } else if (!messages.empty()) {
            messages.back().lines.emplace_back(line);
        }
    }
    if (!entries.empty()) {
        trim(entries.back());
    }
    return entries;
}

std::vector<std::string> elog_lines(const std::vector<ElogEntry>& entries) {
    std::vector<std::string> lines;
    for (const auto& [package, messages] : entries) {
        for (const auto& [type, phase, text] : messages) {
            for (const auto& line : text) {
                lines.push_back(std::format("{}\telog\t{}\t{}\t{}", package, type, phase, line));
            }
        }
    }
    return lines;
}

} // namespace egraph
